### ISSUE TITLE
build-in string function in Python

### ISSUE THREAD

**Issue by JiaxiangBU** [JiaxiangBU/tutoring2#10]
build-in string function in Python

**Comment by JiaxiangBU** [comment]
![image](https://user-images.githubusercontent.com/15884785/66798617-34d81580-ef41-11e9-9355-199771bdd6fd.png)

**Comment by JiaxiangBU** [comment]
![image](https://user-images.githubusercontent.com/15884785/66798901-f4c56280-ef41-11e9-9930-e973bea6a9c2.png)

**Comment by JiaxiangBU** [comment]
可以参考下这个 notes https://mybinder.org/v2/gh/JiaxiangBU/tutoring2/master?filepath=jinxiaosong%2Fstring-syntax-python.ipynb @slsongge

**Comment by slsongge** [comment]
@JiaxiangBU  辛苦家翔哥，我这边应该不能close。
