### ISSUE TITLE
逐步回归AIC问题

### ISSUE THREAD

**Issue by Captain-Pam** [JiaxiangBU/tutoring2#17]
家翔哥，还是上次的数据（第1和第2列一个作为Y就行），只是这次不是用自变量的P值来确定顺序，而是使用AIC值来确定。因此使用逐步回归step或者MAS包中的stepAIC函数来计算，这两个函数基本都是逐步向后回归，返回是一样的形式，我现在得想法是采用stepAIC或step中的第一步start中返回的信息来确定自变量的重要性，返回的信息里有AIC和每个变量去掉后的AIC值，这个AIC列是按照递增的顺序排的吧，这个顺序的逆序就是每个变量的重要程度递减排下来的吧。但是不知道这样是不是正确，还有就是提取这些AIC和变量的问题。谢谢家翔哥！

**Comment by JiaxiangBU** [comment]
> 家翔哥我提交问题了，提交前面的代码，但不知道怎么提取step（）或者stepAIC（），主要就是要这些自变量的一个相对重要的顺序而已。

@Cobbybaby 我先做一个测试代码给你，估计晚一点给你。

**Comment by JiaxiangBU** [comment]
@Cobbybaby 思宇，我觉得这里还是要给一个统一的变量筛选框架，以为这个框架部分的统计值和整体的统计值不太一致，容易导致辛普森悖论。

具体可以参考下 https://jiaxiangbu.github.io/train_model/analysis/simpson_s_paradox.html#遗漏变量

但是这个的代码，我也会帮你完善下。

**Comment by Captain-Pam** [comment]
谢谢家翔哥，我先看看里面的内容，好像很多我都没学过，正好学习一下

**Comment by JiaxiangBU** [comment]
> 谢谢家翔哥，我先看看里面的内容

好的，回头可以沟通下。
