### ISSUE TITLE
Python中groupby+agg框架中，如何自定义levels[1]的列名？

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring2#2]
### 问题
目前我只会用循环去实现将levels[1]的列名更换，但是我希望使用类似下图橙框区域内的代码（即直接在agg后面写代码实现）实现自定义levels[1]的列名（当然这代码是错误的哈，就是想问有没有类似的方法做到），如下图：

![image](https://user-images.githubusercontent.com/36298417/64062061-1b8b3c00-cc15-11e9-8e96-c60dbef6f404.png)

### 代码
```python
import seaborn as sns
iris = sns.load_dataset('iris')

iris_agg = iris.groupby('species').agg([max, min])
iris_agg

## not run: the code is error
# ris_agg = iris.groupby('species').agg({'MAX':max, 'MIN':min})
```

@JiaxiangBU  辛苦家翔哥！！！

**Comment by slsongge** [comment]
@JiaxiangBU   家翔哥，我找了好久，找了一个相对简单的方法，但是还不是我想要的（或许就没有我想要的方法，只能是像下图一样替换）。

![image](https://user-images.githubusercontent.com/36298417/64063492-4f6f5d00-cc27-11e9-990c-289d6afb4bf2.png)

**Comment by JiaxiangBU** [comment]
@slsongge 晓松，复现例子见 https://mybinder.org/v2/gh/JiaxiangBU/tutoring2/master?filepath=jinxiaosong%2Fgroup_by%2Fgroupby-apply.ipynb

1. `?pd.DataFrame.unstack` 查询 `unstack` 用法。
2. https://jiaxiangli.netlify.com/2018/02/04/pandas-cookbook/#unstack 查询 `sort_index` 和 `swaplevel` 的用法
3. https://jiaxiangbu.github.io/learn_python/analysis/pandas/learning_notes.html#join-1 查询 apply + lambda 用法

**Comment by JiaxiangBU** [comment]
Python 代码我记得你之前也问了一些，我直接给你写了下解释~~~应该可以理解的。

**Comment by JiaxiangBU** [comment]
李家翔: 但是我觉得步骤好多好麻烦哈哈~
靳晓松: 确实是
李家翔: 你可以想想有没有更加简单的。。。

- [ ] 李家翔: lambda 是核心，后面的估计可以简化！
