### ISSUE TITLE
R语言学习的模块

### ISSUE THREAD

**Issue by hehuanshu96** [JiaxiangBU/tutoring2#25]
> 「洪七：所以可能会侧重绘图，数据整理，计量分析，以及最新的机器学习。不过我刚开始啊」
> - - - - - - - - - - - - - - -
> 哦哦哦，好几个模块啊~~~

- 前面数据清洗方面，先搞 tidyverse https://jiaxiangbu.github.io/book2tidyverse/book.html
- 然后绘图搞 ggplot2 https://jiaxiangbu.github.io/r_eda/designing_ggplots/learning_notes.html
- 计量看面板数据 https://jiaxiangbu.github.io/learn_longitudinal_analysis/
- 机器学习看 xgboost https://jiaxiangli.netlify.com/2018/02/02/xgboost-r-tutorial/
- 系统 notes https://jiaxiangbu.github.io/r_code/

***

还有一部分使用 purrr 包的部分，比较难，先看完 book2tidyverse 我再放哈 @hehuanshu96

**Comment by hehuanshu96** [comment]
install.packages("xgboost", repos="http://dmlc.ml/drat/", type = "source")
Warning in install.packages :
  unable to access index for repository http://dmlc.ml/drat/src/contrib:
  畸形'<!DOCTYPE html> ...'开头行!
Warning in install.packages :
  package ‘xgboost’ is not available (for R version 3.6.2)

**Comment by hehuanshu96** [comment]
无法安装xgboost，标注版本下无法安装

**Comment by JiaxiangBU** [comment]
* [R 数据导入学习笔记](https://jiaxiangbu.github.io/r_code/analysis/import-data-learning-notes.html)
* [R 函数化编程学习笔记](https://jiaxiangbu.github.io/r_code/analysis/func-progmm-learning-notes.html)
* [R 数据清洗学习笔记](https://jiaxiangbu.github.io/r_code/analysis/cleaning-data-learning-notes.html)
