### ISSUE TITLE
无法安装xgboost，标注版本下无法安装

### ISSUE THREAD

**Issue by JiaxiangBU** [JiaxiangBU/tutoring2#27]
```r
install.packages("xgboost", repos="http://dmlc.ml/drat/", type = "source")
Warning in install.packages :
  unable to access index for repository http://dmlc.ml/drat/src/contrib:
  畸形'<!DOCTYPE html> ...'开头行!
Warning in install.packages :
  package ‘xgboost’ is not available (for R version 3.6.2)
```
_Originally posted by @hehuanshu96 in https://github.com/JiaxiangBU/tutoring2/issues/25#issuecomment-583829971_

**Comment by JiaxiangBU** [comment]
Xgboost 这个包直接用 R CRAN 的镜像就可以，不需要用'dmlc.ml'的。
其中选择国内的镜像(mirrors.tuna.tsinghua.edu.cn)下载快一些，其中清华的比中科大、同济的都要稳定。

```r
> install.packages("xgboost")
试开URL’https://mirrors.tuna.tsinghua.edu.cn/CRAN/bin/windows/contrib/3.6/xgboost_0.90.0.2.zip'
Content type 'application/zip' length 2333360 bytes (2.2 MB)
downloaded 2.2 MB

package ‘xgboost’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\lijiaxiang\AppData\Local\Temp\RtmpsPAbwg\downloaded_packages
```

镜像的设置方法，打开RStudio，点击 Tools，Global Options，Packages，

![image](https://user-images.githubusercontent.com/15884785/74102531-290eff80-4b7f-11ea-8c2e-dbd4d83291df.png)

更多参考 https://jiaxiangli.netlify.com/2017/12/08/r-rstudio/

如果还不行的话，下次跑这行命令`sessionInfo()`，把输出都复制上来我看下。

**Comment by hehuanshu96** [comment]
搞定啦。多谢

**Comment by JiaxiangBU** [comment]
@hehuanshu96 issue closed
