### ISSUE TITLE
R计量结果输出，类似STATA中的outreg2命令。多谢啦

### ISSUE THREAD

**Issue by hehuanshu96** [JiaxiangBU/tutoring2#28]
「洪七：找到一个，不好的地方是R输出为html，但用word打开貌似还可以的样子」
- - - - - - - - - - - - - - -
是的就是这个样子的，这是一种，还有一个是 rstudio官方的 gt，也可以，打死你不是完全打印体

R计量结果输出，类似STATA中的outreg2命令。多谢啦

问题解决后，记得 close。

**Comment by JiaxiangBU** [comment]
- stargazer 参考这个 notes https://jiaxiangbu.github.io/learn_stargazer/learn_notes.html
- gt 参考项目 https://github.com/JiaxiangBU/learn_gt

@hehuanshu96
