### ISSUE TITLE
数据框某列分段方法

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring2#30]
### 问题
在python中，对数据框的某列使用if-else语法进行分段？

### 代码
```python
import pandas as pd
import numpy as np

np.random.seed(12)
age = np.random.randint(low = 0, high = 100, size = 1000)
df_raw = pd.DataFrame({'age': age})

## 方法一：pd.cut()
df_raw['age_cut_1'] = pd.cut(df_raw['age'], bins=[0,18,30,60,1000], right=False, labels=['A','B','C','D'])

## 方法二：np.select()
conditions = [(df_raw['age'] < 18), 
              (df_raw['age'] < 30), 
              (df_raw['age'] < 60), 
              (df_raw['age'] >= 60)]
choices = ['A','B','C','D']
df_raw['age_cut_2'] = np.select(conditions, choices)

## 方法三：if-else
````

**Comment by JiaxiangBU** [comment]
https://github.com/JiaxiangBU/tutoring2/issues/30


```python
import pandas as pd
import numpy as np

np.random.seed(12)
age = np.random.randint(low = 0, high = 100, size = 1000)
df_raw = pd.DataFrame({'age': age})
```


```python
## 方法一：pd.cut()
df_raw['age_cut_1'] = pd.cut(df_raw['age'], bins=[0,18,30,60,1000], right=False, labels=['A','B','C','D'])
```


```python
df_raw.head()
```




<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>age</th>
      <th>age_cut_1</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>75</td>
      <td>D</td>
    </tr>
    <tr>
      <th>1</th>
      <td>27</td>
      <td>B</td>
    </tr>
    <tr>
      <th>2</th>
      <td>6</td>
      <td>A</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2</td>
      <td>A</td>
    </tr>
    <tr>
      <th>4</th>
      <td>3</td>
      <td>A</td>
    </tr>
  </tbody>
</table>
</div>




```python
## 方法二：np.select()
conditions = [(df_raw['age'] < 18), 
              (df_raw['age'] < 30), 
              (df_raw['age'] < 60), 
              (df_raw['age'] >= 60)]
choices = ['A','B','C','D']
df_raw['age_cut_2'] = np.select(conditions, choices)
```


```python
df_raw.head()
```




<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>age</th>
      <th>age_cut_1</th>
      <th>age_cut_2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>75</td>
      <td>D</td>
      <td>D</td>
    </tr>
    <tr>
      <th>1</th>
      <td>27</td>
      <td>B</td>
      <td>B</td>
    </tr>
    <tr>
      <th>2</th>
      <td>6</td>
      <td>A</td>
      <td>A</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2</td>
      <td>A</td>
      <td>A</td>
    </tr>
    <tr>
      <th>4</th>
      <td>3</td>
      <td>A</td>
      <td>A</td>
    </tr>
  </tbody>
</table>
</div>




```python
# https://mp.weixin.qq.com/s/6Kda5qGzX6IZyYi8McDruA
# https://blog.csdn.net/weixin_39750084/article/details/103437665
# 不要忘记 return
def int2cat(x):
    if x < 18:
        return 'A'
    elif x < 30:
        return 'B'
    elif x < 60:
        return 'C'
    elif x >= 60:
        return 'D'
    else:
        return 'E'
```


```python
df_raw['age'].apply(int2cat).head()
```




    0    D
    1    B
    2    A
    3    A
    4    A
    Name: age, dtype: object




```python
# https://stackoverflow.com/questions/9987483/elif-in-list-comprehension-conditionals
df_raw['age'].apply(lambda age: 'A' if age < 18 else 'B' if age < 30 else 'C' if age < 60 else 'D').head()
```




    0    D
    1    B
    2    A
    3    A
    4    A
    Name: age, dtype: object




```python

```

**Comment by JiaxiangBU** [comment]
@slsongge 晓松，见 commit https://github.com/JiaxiangBU/tutoring2/commit/cffbe1df7e1d824a58be2aff3eb3dae4b1d0f8e6 见 [notebook](https://mybinder.org/v2/gh/JiaxiangBU/tutoring2/master?filepath=jinxiaosong%2Fif-else.ipynb)
