### ISSUE TITLE
关于Git简易教程以及我这边安装没有公密钥（Git (2.25.1) 64-bit version of Git for Windows. ）

### ISSUE THREAD

**Issue by hehuanshu96** [JiaxiangBU/tutoring2#36]
参考 https://jiaxiangbu.github.io/learn_git/output/git-github-gitlab-learning-notes.html

**Comment by hehuanshu96** [comment]
关于Git简易教程以及我这边安装没有公密钥（Git (2.25.1) 64-bit version of Git for Windows. ）

**Comment by JiaxiangBU** [comment]
> 关于Git简易教程以及我这边安装没有公密钥（Git (2.25.1) 64-bit version of Git for Windows. ）


> 参考 https://jiaxiangbu.github.io/learn_git/output/git-github-gitlab-learning-notes.html

@hehuanshu96 **5.6 设置 SSH 钥匙**
