### ISSUE TITLE
文本相似比较

### ISSUE THREAD

**Issue by hehuanshu96** [JiaxiangBU/tutoring2#38]
有两个文本，提取高频词汇对比，或者文本相似性对比。
类似教程么，多谢多谢李老师

**Comment by JiaxiangBU** [comment]
可以主要查看这个 notes https://jiaxiangbu.github.io/learn_nlp/analysis/text-mining-learning-notes.html

> 提取高频词汇对比

需要先分词，因此查看分词模块。
然后进行文本的 count 就好。

之后做文本相似性，算下皮尔森相关系数，我觉得可以简单计算一下了。 @hehuanshu96
