### ISSUE TITLE
python 批量导出和导入

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring2#48]
### 问题
如何在python中，批量导出n个数据框为csv或者xlsx格式？

### 数据框格式
每个数据框的列名完全相同

### 目前实现方法
![image](https://user-images.githubusercontent.com/36298417/77826383-ebbffa80-7149-11ea-8c88-65cc6755aae1.png)

**Comment by JiaxiangBU** [comment]
参考

1. `jinxiaosong/concatenate-csv.ipynb`

这是假设的三个表格

1. `jinxiaosong/data/df1.csv` 
1. `jinxiaosong/data/df2.csv`
1. `jinxiaosong/data/df3.csv`

**批量导入**，主要就是 for 循环加上 append 完成就好了。
**批量导出**，主要就是 pd.DataFrame.groupby 加上 for 循环

导出文件如

1. `jinxiaosong/data/outputdf1.csv.csv`
1. `jinxiaosong/data/outputdf2.csv.csv`
1. `jinxiaosong/data/outputdf3.csv.csv`

```python
for idx, i in df.groupby('groups'):
    file_name = 'output' + str(idx) + '.csv'
    i.to_csv(os.path.join('data',file_name))
```


@slsongge
