### ISSUE TITLE
reticulate 卸载python package

### ISSUE THREAD

**Issue by liangzp** [JiaxiangBU/tutoring2#52]
希望用rbookdown的笔记中运行python，其中需要导入keras package，但是我的keras貌似版本不对，在rbookdown中插入一个chunk运行代码：
```python
import keras
```
输出信息
>ModuleNotFoundError: No module named 'tensorflow.python.eager'
Detailed traceback: 
  File "<string>", line 1, in <module>
  File "/Users/zhipengliang/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/Users/zhipengliang/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/Users/zhipengliang/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/Users/zhipengliang/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/Users/zhipengliang/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/Users/zhipengliang/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 6, in <module>
    from tensorflow.python.eager import context

我想卸载keras重装正确的版本，但是貌似只有安装的命令py_install，conda_remove又显示:
```python
> conda_remove(keras)
Error in envname %||% Sys.getenv("RETICULATE_PYTHON_ENV", unset = "r-reticulate") : 
  object 'keras' not found
```

现在想知道怎么在reticulate卸载python package

**Comment by JiaxiangBU** [comment]
这个直接用`pip uninstall keras`？ @liangzp

**Comment by liangzp** [comment]
怀疑reticulate没有Pypi对应的uninstall的函数：
[官方文档](https://rstudio.github.io/reticulate/articles/python_packages.html)
![image](https://user-images.githubusercontent.com/23372592/79989739-c9b85e80-84e2-11ea-96e5-2a710abc3d10.png)
可以看到官方文档没出现Pypi对应的uninstall函数，而conda有一个conda_remove，但是运行结果很奇怪：
![image](https://user-images.githubusercontent.com/23372592/79989948-07b58280-84e3-11ea-8c76-515d920c13ae.png)
（我的rmarkdown下的确安装了keras）

**Comment by JiaxiangBU** [comment]
@liangzp 

> 怀疑reticulate没有Pypi对应的uninstall的函数：
> [官方文档](https://rstudio.github.io/reticulate/articles/python_packages.html)
> ![image](https://user-images.githubusercontent.com/23372592/79989739-c9b85e80-84e2-11ea-96e5-2a710abc3d10.png)
> 可以看到官方文档没出现Pypi对应的uninstall函数，而conda有一个conda_remove，但是运行结果很奇怪：
> ![image](https://user-images.githubusercontent.com/23372592/79989948-07b58280-84e3-11ea-8c76-515d920c13ae.png)
> （我的rmarkdown下的确安装了keras）

这有个不好的影响就是在 RMarkdown 要搭建一个新的环境，已经类似于`conda create`，但是这里其实没有环境隔离的需求，更好的体验是 RMarkdown 使用的包，和 jupyter notebook 打开某个环境使用的包共用。

所以安装包还是在指定的环境里面安装，用`pip install`，更多参考 https://jiaxiangbu.github.io/learn_python/analysis/conda/01-conda_notes.html

那么RMarkdown 里面指定对应的 Python，参考 https://jiaxiangbu.github.io/learn_nn/use_python_in_r

**Comment by liangzp** [comment]
![image](https://user-images.githubusercontent.com/23372592/80071315-f9b14180-8576-11ea-931b-bfb17991181e.png)
我的base环境下面有三个路径，应该怎么把另外两个去掉呢？

**Comment by JiaxiangBU** [comment]
> ![image](https://user-images.githubusercontent.com/23372592/80071315-f9b14180-8576-11ea-931b-bfb17991181e.png)
> 我的base环境下面有三个路径，应该怎么把另外两个去掉呢？



> 更多参考 https://jiaxiangbu.github.io/learn_python/analysis/conda/01-conda_notes.html

**12 删除环境** 这一部分 @liangzp

**Comment by liangzp** [comment]
最后直接删除对应路径下的r-miniconda文件夹即可

**Comment by JiaxiangBU** [comment]
> 现在想知道怎么在reticulate卸载python package

这是独立开发的一个包，应该可以解决这个问题 [rminiconda](https://slides.com/hafen/rminiconda#/25) @liangzp
