### ISSUE TITLE
根据某列连续相同的值分组

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring2#55]
### 问题
按照D列分组，D列只有两种唯一值（0、1），把连续的0或者1作为一组，最后生成n个数据框。

### 代码
```r
library(tidyverse)

set.seed(45L)
df <- tibble(
  A = runif(10, 0, 1),
  B = runif(10, 0, 1),
  D = c(0,0,0,1,1,1,1,0,0,1)
)
```

**Comment by JiaxiangBU** [comment]
@slsongge https://github.com/JiaxiangBU/tutoring2/blob/a526ac133671fe61a25784781e70e81baef3a1e4/jinxiaosong/nested.md
