### ISSUE TITLE
compilation failed of R

### ISSUE THREAD

**Issue by zxy1555847** [JiaxiangBU/tutoring2#58]
> 目前我看截图，只能判断这是一个 MacOS 或者是 Linux 系统，不太清楚你的版本问题。你方便在我的 repo 提交一个 issue 嘛？
> 里面方便我们以代码框的形式，看一些你的 session information。
> 
> 另外告知下你看我的那一部分 notes，我去看下，可以对症下药。

**Comment by JiaxiangBU** [comment]
@zxy1555847 需要一下你提供这些信息？

**Comment by zxy1555847** [comment]
我还不是很会用github，然后好像写了三个，最后一个是我真正想写的
我不知道为什么好像并不是全部显示，我写的所有的文本是这样的：


我目前在服务器上使用R，这个R是由conda安装。我按照
if (!require("devtools")) install.packages("devtools")
devtools::install_github("thierrygosselin/radiator")
library(radiator)
的方法去安装radiator，执行第一条代码就报错compilation failed。

然后我想先在自己的电脑（windows，R版本4.0.2）上试着安装一下，
devtools可以正常安装，但是第二条代码devtools::install_github("thierrygosselin/radiator")，需要rtools，我又装了rtools4.0，然后报没有rlang包的错，我利用install.packages("rlang")命令装rlang，报了compilation
failed的错。


<!-- ### 简述问题
 也就是目前的linux系统下，conda装的R4.0.2报compilation failed，
我自己的电脑，也是报错如此。
我刚接触利用R分析我的数据，主要是想用radiator这个包，也就是我之前没有对我的R进行任何配置，我也不熟悉R，这个问题已经是我能力之外了！所以请求帮助！！

<!-- ### 希望输出的结果
希望，我有生之年可以安装好radiator。


服务器报错：
ERROR: compilation failed for package ‘roxygen2’
* removing
‘/home/mee/public/yaotianyi/conda/condabiosoft/lib/R/library/roxygen2
                               ’
ERROR: dependency ‘later’ is not available for package ‘promises’
* removing
‘/home/mee/public/yaotianyi/conda/condabiosoft/lib/R/library/promises
                               ’
ERROR: dependency ‘fs’ is not available for package ‘usethis’
* removing
‘/home/mee/public/yaotianyi/conda/condabiosoft/lib/R/library/usethis’
ERROR: dependency ‘promises’ is not available for package ‘DT’
* removing ‘/home/mee/public/yaotianyi/conda/condabiosoft/lib/R/library/DT’
ERROR: dependencies ‘usethis’, ‘DT’, ‘roxygen2’ are not available for
package ‘d                                      evtools’
* removing
‘/home/mee/public/yaotianyi/conda/condabiosoft/lib/R/library/devtools
                               ’

The downloaded source packages are in
        ‘/tmp/RtmpSY5M5z/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages("devtools") :
  installation of package ‘later’ had non-zero exit status
2: In install.packages("devtools") :
  installation of package ‘fs’ had non-zero exit status
3: In install.packages("devtools") :
  installation of package ‘roxygen2’ had non-zero exit status
4: In install.packages("devtools") :
  installation of package ‘promises’ had non-zero exit status
5: In install.packages("devtools") :
  installation of package ‘usethis’ had non-zero exit status
6: In install.packages("devtools") :
  installation of package ‘DT’ had non-zero exit status
7: In install.packages("devtools") :
  installation of package ‘devtools’ had non-zero exit status
>





自己电脑报错：
install.packages("rlang")

  There is a binary version available but the source version is later:
      binary source needs_compilation
rlang  0.4.6  0.4.7              TRUE

installing the source package ‘rlang’

trying URL 'https://cran.rstudio.com/src/contrib/rlang_0.4.7.tar.gz'
Content type 'application/x-gzip' length 847308 bytes (827 KB)
downloaded 827 KB

* installing *source* package 'rlang' ...
** 成功将'rlang'程序包解包并MD5和检查
** using staged installation
** libs

*** arch - i386
"c:/rtools40/mingw32/bin/"gcc  -I"D:/PROGRA~2/R-40~1.2/include" -DNDEBUG
-I./lib/         -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign
-c capture.c -o capture.o
sh: c:/rtools40/mingw32/bin/gcc: No such file or directory
make: *** [D:/PROGRA~2/R-40~1.2/etc/i386/Makeconf:222: capture.o] Error 127
ERROR: compilation failed for package 'rlang'
* removing 'D:/Program Files (x86)/R-4.0.2/library/rlang'
Warning in install.packages :
  installation of package ‘rlang’ had non-zero exit status

The downloaded source packages are in
‘C:\Users\MACHENIKE\AppData\Local\Temp\RtmpMjEdNG\downloaded_packages’
>


Jiaxiang Li <notifications@github.com> 于2020年7月15日周三 下午4:22写道：

**Comment by JiaxiangBU** [comment]
@zxy1555847 

> 执行第一条代码就报错compilation failed。

编译问题会比较复杂，因为你可能刚接触R，去和 R core team 反馈这个问题，可能很多信息不知道怎么反馈。

我的思路是

1. 先帮你配置好一个稳定的环境，正常用 R
1. 后面再整理这些信息，跟 core team 提交 bug

我最近有一个同学 @Leaf-Xiao 也出现这个问题，也是在 Windows 10，R 4.0.2 和 最新 RStudio 1.3.x。Rtools 是 4.0 的。
**你介意用一个稳定版本？牺牲一些特性么？**也就是回退的情况，可能你不太能够用到

1. RStudio 1.3.x 的新特性
1. `data.frame` 会默认把 string 变量转换成 factor 的这样操作(有时候会影响干扰数据清洗)

但是稳定，
我给你的配置如下。

```python
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)
```

这些都是在国外服务器上，如果你下载有困难，告诉我，我邮件传给你(RStudio>100MB)。

安装顺序

1. R 3.6.0 https://cran.r-project.org/bin/windows/base/old/3.6.0/
1. RStudio https://rstudio.com/products/rstudio/older-versions/ 找一个 1.2.x 的
1. Rtools 3.5 https://cran.r-project.org/bin/windows/Rtools/history.html
1. 再安装 devtools 这是一个集成包，会很慢，最好设置下 RStudio 的镜像
**1.0.0.3 安装重要的包**
https://jiaxiangbu.github.io/r_code/analysis/import-data-learning-notes.html

严格按照以上顺序，中间产生 bug，就停下来反馈 bug。

**Comment by zxy1555847** [comment]
好的！非常感谢！我先执行试试。
后期有问题，我再回来追帖。非常感谢您的时间和精力！

**Comment by Leaf-Xiao** [comment]
@JiaxiangBU 第四步安装无法访问网站

**Comment by JiaxiangBU** [comment]
> @JiaxiangBU 第四步安装无法访问网站

@Leaf-Xiao 这个链接访问不了对么？

> 4\. 再安装 devtools 这是一个集成包，会很慢，最好设置下 RStudio 的镜像
>     **1.0.0.3 安装重要的包**
>     https://jiaxiangbu.github.io/r_code/analysis/import-data-learning-notes.html

使用这个 backup 的 gitee pages

http://jiaxiangli.gitee.io/r_code/analysis/import-data-learning-notes.html

**Comment by Leaf-Xiao** [comment]
@JiaxiangBU 可是点开Rstudio显示：无法访问此网站  所有的菜单栏都无法点击
要不我先试试蕾蕾姐密钥的方式吧

**Comment by JiaxiangBU** [comment]
> @JiaxiangBU 可是点开Rstudio显示：无法访问此网站 所有的菜单栏都无法点击
> 要不我先试试蕾蕾姐密钥的方式吧

截图看我下，这个理论上和 git、SSH 没关系。
和你的 Windows 10、RStudio 的版本安装有问题。 @zxy1555847 你现在也遇到这个问题么？



> 安装顺序
> 
> 1. R 3.6.0 https://cran.r-project.org/bin/windows/base/old/3.6.0/
> 2. RStudio https://rstudio.com/products/rstudio/older-versions/ 找一个 1.2.x 的
> 3. Rtools 3.5 https://cran.r-project.org/bin/windows/Rtools/history.html
> 4. 再安装 devtools 这是一个集成包，会很慢，最好设置下 RStudio 的镜像
>    **1.0.0.3 安装重要的包**
>    https://jiaxiangbu.github.io/r_code/analysis/import-data-learning-notes.html
> 
> 严格按照以上顺序，中间产生 bug，就停下来反馈 bug。

@Leaf-Xiao 我现在想确认，你应该不是第四步出现问题，而是第二步就出现问题了吧？

**Comment by Leaf-Xiao** [comment]
第二步安装完全没问题，但是打开显示无法访问；因为你这里是说要按照步骤进行，我以为全部安装后就没问题了；但到第四步是首先网址无法打开，第二看到给的笔记里需要用到RStudio,但打开RStudio后还是显示：无法访问。我在网上也查了相应的方法，但是还是无法解决。 @JiaxiangBU

**Comment by JiaxiangBU** [comment]
@Leaf-Xiao 我没有理解问题安装成功但是打不开对么？
里面你安装的版本有严格按照我给你的么？



> 安装顺序
> 
> 1. R 3.6.0 https://cran.r-project.org/bin/windows/base/old/3.6.0/
> 2. RStudio https://rstudio.com/products/rstudio/older-versions/ 找一个 1.2.x 的
> 3. Rtools 3.5 https://cran.r-project.org/bin/windows/Rtools/history.html
> 4. 再安装 devtools 这是一个集成包，会很慢，最好设置下 RStudio 的镜像
>    **1.0.0.3 安装重要的包**
>    https://jiaxiangbu.github.io/r_code/analysis/import-data-learning-notes.html
> 
> 严格按照以上顺序，中间产生 bug，就停下来反馈 bug。

四个软件的版本号，按照版本号找到对应的软件。

另外我需要你截个图，我看一下具体问题是什么情况。因为这个是一个本地软件，不需要联网，所以很奇怪。

**Comment by Leaf-Xiao** [comment]
@JiaxiangBU 
版本的确是按照你给我的安装的
如图：
<img width="785" alt="捕获" src="https://user-images.githubusercontent.com/67859065/87786283-418cef80-c86c-11ea-8caf-e9bc89337ecf.PNG">
<img width="90" alt="捕获2" src="https://user-images.githubusercontent.com/67859065/87786306-4baeee00-c86c-11ea-9106-ef7cb5d5e446.PNG">
<img width="98" alt="捕获3" src="https://user-images.githubusercontent.com/67859065/87786322-523d6580-c86c-11ea-8801-59f7ab4a827b.PNG">

**Comment by JiaxiangBU** [comment]
> RStudio
> 无法访问此网站网址为http://127.0.0.1:41880/的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
> ERR FAILED
> 

@Leaf-Xiao 安装版本没有问题，都是回退的版本了。

那么有其他原因需要排查。

1. R 和 RStudio 安装路径是否包含了 non-ASCII 文本，如[中文](https://ask.csdn.net/questions/772248)
路径在(用git bash)打开，输入
```bash
where R
```
1. 更复杂些，host 文件，打开下复制下内容给我？这里面不包含隐私信息。
路径在(用git bash)打开，输入
```bash
cat /etc/hosts
```

**Comment by zxy1555847** [comment]
ok。我来给反馈啦！
前4步都非常正常，然后我用新的R和Rstudio和Rtools进行包的安装，发现在devtools包的安装过程中，还是有安装不上的依赖包，
Warning in install.packages :
  installation of package ‘processx’ had non-zero exit status
Warning in install.packages :
  installation of package ‘fs’ had non-zero exit status
Warning in install.packages :
  installation of package ‘Rcpp’ had non-zero exit status
对于这几个包的源码包是已经下载好了的，所以我想手动安装，命令：install.packages("processx")
结果还是报非零推出的错，因此我又在install时选择加载本地包，因为的源码包（.tar.gz）是有的，
 install.packages("C:/Users/MACHENIKE/AppData/Local/Temp/RtmpMBS314/downloaded_packages/processx_3.4.3.tar.gz", repos = NULL, type = "source")
结果还是报非零退出的错误，
Warning in install.packages :
  installation of package ‘C:/Users/MACHENIKE/AppData/Local/Temp/RtmpMBS314/downloaded_packages/processx_3.4.3.tar.gz’ had non-zero exit status
因此，我认为的结论是：就算我安装的old version的一套R，也还是没能解决部分包编译失败的报错。

**Comment by zxy1555847** [comment]
朋友们，我在知乎上找到 这个：
ERROR: compilation failed for package
经常出现在OSX中的一个问题，**缺**少C++ library 提供的放头文件****。解决办法是安装C++或者Xcode Command Line Tools。C++的安装不必说，Xcode Command Line Tools 的安装命令为：

xcode-select --install
安装Xcode Command Line Tools 就不会在发生 compilation failed for package 的错误了。

这不就是我们的错误嘛。然后，他给的这个xcode是苹果系统的，至于linux和windows，应该也有相应的包，缺少C++ library提供的放头文件，我并看不懂。

**Comment by JiaxiangBU** [comment]
> 朋友们，我在知乎上找到 这个：

这个链接发我看下？ @zxy1555847

**Comment by zxy1555847** [comment]
https://zhuanlan.zhihu.com/p/46077702

**Comment by zxy1555847** [comment]
朋友们，我解决掉这个问题了！
但是我不保证屡试不爽哈！
代码如下：


```
update.packages(ask=F)
remove.packages("rlang")
remove.packages("gsl")
remove.packages("Rcpp")
# 重启R语言
# 在RStudio里面可以点击菜单栏的`Session -> Restart R`，或使用快捷键`Ctrl+Shift+F10`
install.packages("rlang")
install.packages("gsl")
install.packages("Rcpp")

```


ok!至此，我在安装包的时候，就会报别的错了，但是不会报编译的错。
从这个帖子学来的：
https://github.com/psychbruce/bruceR/blob/master/Installation%20Bugs%20and%20Solutions.md

**Comment by zxy1555847** [comment]
我不知道为什么写出来之后重启的字这么大，但是并不是强调，不影响使用！

**Comment by JiaxiangBU** [comment]
@zxy1555847 

我参考 https://zhuanlan.zhihu.com/p/46077702
```
xcode-select --install
```

xcode 这个确切说是 MacOS 要安装和更新的软件，不是 Windows 的版本问题了。

```
sudo apt-get install r-base-core
```

`apt-get`说明你是 Ubuntu 的系统？

这部分我原来在阿里云上安装R，配置过。

而且现在的问题是安装一些包有依赖问题？
我之前也遇到过，把这些 dependencies 安装好，devtools 就可以安装了。

参考 3.2 R和RStudio
https://jiaxiangbu.github.io/learn_linux/linux-learning-notes.html#r和rstudio

**Comment by JiaxiangBU** [comment]
> 我不知道为什么写出来之后重启的字这么大，但是并不是强调，不影响使用！

好的，需要用代码框表示，我修改改了，你有兴趣可以点一下 edit 查看下 @zxy1555847

**Comment by zxy1555847** [comment]
知乎的那条帖子我没有仔细看，我们实验室的服务器的确是ubuntu的系统，但是我很少会sudo。
我现在已经依照我给的代码配置好我的 R了，我的包也已经装好了。主要的问题症结就是缺少Rcpp包。
ok！非常感谢指导！我的朋友！

**Comment by JiaxiangBU** [comment]
> 知乎的那条帖子我没有仔细看，我们实验室的服务器的确是ubuntu的系统，但是我很少会sudo。
> 我现在已经依照我给的代码配置好我的 R了，我的包也已经装好了。主要的问题症结就是缺少Rcpp包。
> ok！非常感谢指导！我的朋友！

好啊，那我感觉你的没有问题了。Rcpp 是一个很核心的包，现在有1200个发布的包都用到它，你看下安装是否还有问题。 @zxy1555847

**Comment by zxy1555847** [comment]
目前没了！！Thank you very much！

**Comment by Leaf-Xiao** [comment]
@JiaxiangBU 
R的安装路径：**C:\Program Files\R\R-3.6.0**  
RStudio的安装路径：**C:\Program Files\RStudio**
这两个应该是没有中文或者其他non-ASCII 文本

**此外hosts：**
<img width="445" alt="捕获" src="https://user-images.githubusercontent.com/67859065/87868668-e6bdda00-c9ca-11ea-8cc1-c8afc6853fa1.PNG">

**Comment by JiaxiangBU** [comment]
@Leaf-Xiao 

> R的安装路径：**C:\Program Files\R\R-3.6.0**
> RStudio的安装路径：**C:\Program Files\RStudio**
> 这两个应该是没有中文或者其他non-ASCII 文本

那么你的用户名呢？在`C:\Users`下面，如果是报错中文的，一般两种方案

1. 新建用户为英文的
1. 把R和RStudio 不要装在这个路径下，如装在 D 盘。

另外，用管理员权限打开，参考 https://zhuanlan.zhihu.com/p/82495772
