### ISSUE TITLE
python：实现透视表中占比功能

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring2#61]
我有一个数据框，四列：A、B、C、D
D：是按照前三列分组进行的agg('count')

现在我要只对A、B分组，求D的count，然后对A分组求D的count，接下来join，最后求D的占比

### 数据
[pivot_help.xlsx](https://github.com/JiaxiangBU/tutoring2/files/5249202/pivot_help.xlsx)

### 我的实现代码
```python
import pandas as pd

df_raw = pd.read_excel("D:/pivot_help.xlsx")
df_raw.head()

#### 衍生占比【这段代码用了两次聚合，一次merge，太麻烦了，我想要进行优化】
df_gb_cut_sum = df_raw.groupby('cut')['n'].agg(['sum']).reset_index()
df_gb_cut_color_sum = df_raw.groupby(['cut','color'])['n'].agg(['sum']).reset_index()

df_join = df_gb_cut_color_sum.merge(df_gb_cut_sum, how='left', on='cut')
df_join['prob'] = df_join['sum_x'] / df_join['sum_y']


#### 调整为支持可视化的数据
df_join_plot = pd.DataFrame(
    df_join \
      .drop(columns=['sum_x','sum_y'], axis=1) \
      .pivot(index='cut', columns='color', values='prob') \
      .to_records()
)

df_join_plot
```
@JiaxiangBU

**Comment by JiaxiangBU** [comment]
> ```python
> df_gb_cut_sum = df_raw.groupby('cut')['n'].agg(['sum']).reset_index()
> df_gb_cut_color_sum = df_raw.groupby(['cut','color'])['n'].agg(['sum']).reset_index()
> 
> df_join = df_gb_cut_color_sum.merge(df_gb_cut_sum, how='left', on='cut')
> df_join['prob'] = df_join['sum_x'] / df_join['sum_y']
> ```

我看了下代码，其实你要做的是

1. 在对`cut`每一个分类里面，求聚合。
1. 在某一个`cut`里面，对`color`的算`n`的占比。

想要上面两步想要一次性完成。 @slsongge

**Comment by JiaxiangBU** [comment]
@slsongge 


``` r
list(untracked = "jinxiaosong/analysis/some_join.ipynb",
     untracked = "jinxiaosong/data/pivot_help.xlsx")
    # add @slsongge data
```

``` python
import pandas as pd
```

``` python
df_raw = pd.read_excel("../data/pivot_help.xlsx")
# df_raw.head()
```

``` python
df_raw.info()
```

    <class 'pandas.core.frame.DataFrame'>
    RangeIndex: 276 entries, 0 to 275
    Data columns (total 4 columns):
     #   Column   Non-Null Count  Dtype 
    ---  ------   --------------  ----- 
     0   cut      276 non-null    object
     1   color    276 non-null    object
     2   clarity  276 non-null    object
     3   n        276 non-null    int64 
    dtypes: int64(1), object(3)
    memory usage: 8.8+ KB

``` python
#### 衍生占比【这段代码用了两次聚合，一次merge，太麻烦了，我想要进行优化】
df_gb_cut_sum = df_raw.groupby('cut')['n'].agg(['sum']).reset_index()
df_gb_cut_color_sum = df_raw.groupby(['cut','color'])['n'].agg(['sum']).reset_index()

df_join = df_gb_cut_color_sum.merge(df_gb_cut_sum, how='left', on='cut')
df_join['prob'] = df_join['sum_x'] / df_join['sum_y']
```

``` python
df_join.head(10)
```

<div>

<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table border="1" class="dataframe">

<thead>

<tr style="text-align: right;">

<th>

</th>

<th>

cut

</th>

<th>

color

</th>

<th>

sum\_x

</th>

<th>

sum\_y

</th>

<th>

prob

</th>

</tr>

</thead>

<tbody>

<tr>

<th>

0

</th>

<td>

Fair

</td>

<td>

D

</td>

<td>

163

</td>

<td>

1610

</td>

<td>

0.101242

</td>

</tr>

<tr>

<th>

1

</th>

<td>

Fair

</td>

<td>

E

</td>

<td>

224

</td>

<td>

1610

</td>

<td>

0.139130

</td>

</tr>

<tr>

<th>

2

</th>

<td>

Fair

</td>

<td>

F

</td>

<td>

312

</td>

<td>

1610

</td>

<td>

0.193789

</td>

</tr>

<tr>

<th>

3

</th>

<td>

Fair

</td>

<td>

G

</td>

<td>

314

</td>

<td>

1610

</td>

<td>

0.195031

</td>

</tr>

<tr>

<th>

4

</th>

<td>

Fair

</td>

<td>

H

</td>

<td>

303

</td>

<td>

1610

</td>

<td>

0.188199

</td>

</tr>

<tr>

<th>

5

</th>

<td>

Fair

</td>

<td>

I

</td>

<td>

175

</td>

<td>

1610

</td>

<td>

0.108696

</td>

</tr>

<tr>

<th>

6

</th>

<td>

Fair

</td>

<td>

J

</td>

<td>

119

</td>

<td>

1610

</td>

<td>

0.073913

</td>

</tr>

<tr>

<th>

7

</th>

<td>

Good

</td>

<td>

D

</td>

<td>

662

</td>

<td>

4906

</td>

<td>

0.134937

</td>

</tr>

<tr>

<th>

8

</th>

<td>

Good

</td>

<td>

E

</td>

<td>

933

</td>

<td>

4906

</td>

<td>

0.190175

</td>

</tr>

<tr>

<th>

9

</th>

<td>

Good

</td>

<td>

F

</td>

<td>

909

</td>

<td>

4906

</td>

<td>

0.185283

</td>

</tr>

</tbody>

</table>

</div>

``` python
df_raw.groupby('cut').apply(lambda x: x.groupby('color')['n'].sum()/x['n'].sum())
```

<div>

<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table border="1" class="dataframe">

<thead>

<tr style="text-align: right;">

<th>

color

</th>

<th>

D

</th>

<th>

E

</th>

<th>

F

</th>

<th>

G

</th>

<th>

H

</th>

<th>

I

</th>

<th>

J

</th>

</tr>

<tr>

<th>

cut

</th>

<th>

</th>

<th>

</th>

<th>

</th>

<th>

</th>

<th>

</th>

<th>

</th>

<th>

</th>

</tr>

</thead>

<tbody>

<tr>

<th>

Fair

</th>

<td>

0.101242

</td>

<td>

0.139130

</td>

<td>

0.193789

</td>

<td>

0.195031

</td>

<td>

0.188199

</td>

<td>

0.108696

</td>

<td>

0.073913

</td>

</tr>

<tr>

<th>

Good

</th>

<td>

0.134937

</td>

<td>

0.190175

</td>

<td>

0.185283

</td>

<td>

0.177538

</td>

<td>

0.143090

</td>

<td>

0.106400

</td>

<td>

0.062576

</td>

</tr>

<tr>

<th>

Ideal

</th>

<td>

0.131502

</td>

<td>

0.181105

</td>

<td>

0.177532

</td>

<td>

0.226625

</td>

<td>

0.144541

</td>

<td>

0.097118

</td>

<td>

0.041576

</td>

</tr>

<tr>

<th>

Premium

</th>

<td>

0.116235

</td>

<td>

0.169458

</td>

<td>

0.169023

</td>

<td>

0.212022

</td>

<td>

0.171126

</td>

<td>

0.103546

</td>

<td>

0.058589

</td>

</tr>

<tr>

<th>

Very Good

</th>

<td>

0.125228

</td>

<td>

0.198643

</td>

<td>

0.179109

</td>

<td>

0.190283

</td>

<td>

0.150968

</td>

<td>

0.099652

</td>

<td>

0.056117

</td>

</tr>

</tbody>

</table>

</div>

**Comment by JiaxiangBU** [comment]
@slsongge 


``` r
df <- read_excel("jinxiaosong/data/pivot_help.xlsx")  
```

``` r
df %>%
    group_by(cut,color) %>%
    summarise(pctg = sum(n)) %>% 
    ungroup() %>% 
    group_by(cut) %>% 
    mutate(pctg = pctg/sum(pctg)) %>% 
    spread(color,pctg)
```

    ## # A tibble: 5 x 8
    ## # Groups:   cut [5]
    ##   cut           D     E     F     G     H      I      J
    ##   <chr>     <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl>
    ## 1 Fair      0.101 0.139 0.194 0.195 0.188 0.109  0.0739
    ## 2 Good      0.135 0.190 0.185 0.178 0.143 0.106  0.0626
    ## 3 Ideal     0.132 0.181 0.178 0.227 0.145 0.0971 0.0416
    ## 4 Premium   0.116 0.169 0.169 0.212 0.171 0.104  0.0586
    ## 5 Very Good 0.125 0.199 0.179 0.190 0.151 0.0997 0.0561

我看了下你的代码，我发现你的思路是按照 dplyr 的方式去实现的。 就是说靠函数/pipeline，把每个 scalars
求出来，然后再进行汇总，这是 dplyr 的风格。 也就是是，你在每一次 group\_by
后，都需要统筹全局的去想想。

pandas 更喜欢自定义函数，你分好块，然后只需要思考其中一块怎么 lambda 函数完成，然后向量化操作。

思维上会不太一样。 建议你看一下
<https://github.com/JiaxiangBU/learn_credit_risk/pull/125>

**Comment by slsongge** [comment]
如果对两个变量进行分组，返回的结果就不是数据框了，从而不能进行转置了
```python
df_raw.groupby(by=['cut','clarity']).apply(lambda x: x.groupby('color')['n'].sum()/x['n'].sum())
```

**Comment by JiaxiangBU** [comment]
> 如果对两个变量进行分组，返回的结果就不是数据框了，从而不能进行转置了
> 
> ```python
> df_raw.groupby(by=['cut','clarity']).apply(lambda x: x.groupby('color')['n'].sum()/x['n'].sum())
> ```

这个数据透视表，index 有两个 levels，column 是一个 level，所以这样返回也正常，你想要的反馈结果是什么样子的？回复下我看看，我来调整 apply 对 index 的设置。 @slsongge

**Comment by slsongge** [comment]
@JiaxiangBU 
下图是我现在面临的情况，目前我找到的最简单的方法就是写if判断就好。当然最直接的方法是在当前代码中调整参数。
![image](https://user-images.githubusercontent.com/36298417/93741834-b2130c80-fc1f-11ea-9806-552df48401d5.png)

**Comment by JiaxiangBU** [comment]
@slsongge 


``` python
for i,(j,x) in enumerate(df_raw.groupby(['cut','clarity'])):
    if i <= 0:
        print(i,j,x)
        print(x.__class__)
        x_series = x.groupby('color')['n'].sum()/x['n'].sum()
        print(x_series.__class__)
        x_df = x_series.to_frame().T
        print(x_df.shape)
```

    0 ('Fair', 'I1')      cut color clarity   n
    0   Fair     D      I1   4
    8   Fair     E      I1   9
    15  Fair     F      I1  35
    23  Fair     G      I1  53
    31  Fair     H      I1  52
    38  Fair     I      I1  34
    45  Fair     J      I1  23
    <class 'pandas.core.frame.DataFrame'>
    <class 'pandas.core.series.Series'>
    (1, 7)

因此充分了解其中的结构，固定进行转置`.T`，而不要借助 `groupby` 合并时，默认转置。

``` python
df_raw.groupby(['cut','clarity']).apply(lambda x: pd.DataFrame(x.groupby('color')['n'].sum()/x['n'].sum()).T)
```

<details>

<summary>结果太长。</summary>

<div>

<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table border="1" class="dataframe">

<thead>

<tr style="text-align: right;">

<th>

</th>

<th>

</th>

<th>

</th>

<th>

D

</th>

<th>

E

</th>

<th>

F

</th>

<th>

G

</th>

<th>

H

</th>

<th>

I

</th>

<th>

J

</th>

</tr>

<tr>

<th>

cut

</th>

<th>

clarity

</th>

<th>

</th>

<th>

</th>

<th>

</th>

<th>

</th>

<th>

</th>

<th>

</th>

<th>

</th>

<th>

</th>

</tr>

</thead>

<tbody>

<tr>

<th rowspan="8" valign="top">

Fair

</th>

<th>

I1

</th>

<th>

n

</th>

<td>

0.019048

</td>

<td>

0.042857

</td>

<td>

0.166667

</td>

<td>

0.252381

</td>

<td>

0.247619

</td>

<td>

0.161905

</td>

<td>

0.109524

</td>

</tr>

<tr>

<th>

IF

</th>

<th>

n

</th>

<td>

0.333333

</td>

<td>

NaN

</td>

<td>

0.444444

</td>

<td>

0.222222

</td>

<td>

NaN

</td>

<td>

NaN

</td>

<td>

NaN

</td>

</tr>

<tr>

<th>

SI1

</th>

<th>

n

</th>

<td>

0.142157

</td>

<td>

0.159314

</td>

<td>

0.203431

</td>

<td>

0.169118

</td>

<td>

0.183824

</td>

<td>

0.073529

</td>

<td>

0.068627

</td>

</tr>

<tr>

<th>

SI2

</th>

<th>

n

</th>

<td>

0.120172

</td>

<td>

0.167382

</td>

<td>

0.190987

</td>

<td>

0.171674

</td>

<td>

0.195279

</td>

<td>

0.096567

</td>

<td>

0.057940

</td>

</tr>

<tr>

<th>

VS1

</th>

<th>

n

</th>

<td>

0.029412

</td>

<td>

0.082353

</td>

<td>

0.194118

</td>

<td>

0.264706

</td>

<td>

0.188235

</td>

<td>

0.147059

</td>

<td>

0.094118

</td>

</tr>

<tr>

<th>

VS2

</th>

<th>

n

</th>

<td>

0.095785

</td>

<td>

0.160920

</td>

<td>

0.203065

</td>

<td>

0.172414

</td>

<td>

0.157088

</td>

<td>

0.122605

</td>

<td>

0.088123

</td>

</tr>

<tr>

<th>

VVS1

</th>

<th>

n

</th>

<td>

0.176471

</td>

<td>

0.176471

</td>

<td>

0.294118

</td>

<td>

0.176471

</td>

<td>

0.058824

</td>

<td>

0.058824

</td>

<td>

0.058824

</td>

</tr>

<tr>

<th>

VVS2

</th>

<th>

n

</th>

<td>

0.130435

</td>

<td>

0.188406

</td>

<td>

0.144928

</td>

<td>

0.246377

</td>

<td>

0.159420

</td>

<td>

0.115942

</td>

<td>

0.014493

</td>

</tr>

<tr>

<th rowspan="8" valign="top">

Good

</th>

<th>

I1

</th>

<th>

n

</th>

<td>

0.083333

</td>

<td>

0.239583

</td>

<td>

0.197917

</td>

<td>

0.197917

</td>

<td>

0.145833

</td>

<td>

0.093750

</td>

<td>

0.041667

</td>

</tr>

<tr>

<th>

IF

</th>

<th>

n

</th>

<td>

0.126761

</td>

<td>

0.126761

</td>

<td>

0.211268

</td>

<td>

0.309859

</td>

<td>

0.056338

</td>

<td>

0.084507

</td>

<td>

0.084507

</td>

</tr>

<tr>

<th>

SI1

</th>

<th>

n

</th>

<td>

0.151923

</td>

<td>

0.227564

</td>

<td>

0.175000

</td>

<td>

0.132692

</td>

<td>

0.150641

</td>

<td>

0.105769

</td>

<td>

0.056410

</td>

</tr>

<tr>

<th>

SI2

</th>

<th>

n

</th>

<td>

0.206290

</td>

<td>

0.186864

</td>

<td>

0.185939

</td>

<td>

0.150786

</td>

<td>

0.146161

</td>

<td>

0.074931

</td>

<td>

0.049029

</td>

</tr>

<tr>

<th>

VS1

</th>

<th>

n

</th>

<td>

0.066358

</td>

<td>

0.137346

</td>

<td>

0.203704

</td>

<td>

0.234568

</td>

<td>

0.118827

</td>

<td>

0.158951

</td>

<td>

0.080247

</td>

</tr>

<tr>

<th>

VS2

</th>

<th>

n

</th>

<td>

0.106339

</td>

<td>

0.163599

</td>

<td>

0.188139

</td>

<td>

0.196319

</td>

<td>

0.141104

</td>

<td>

0.112474

</td>

<td>

0.092025

</td>

</tr>

<tr>

<th>

VVS1

</th>

<th>

n

</th>

<td>

0.069892

</td>

<td>

0.231183

</td>

<td>

0.188172

</td>

<td>

0.220430

</td>

<td>

0.166667

</td>

<td>

0.118280

</td>

<td>

0.005376

</td>

</tr>

<tr>

<th>

VVS2

</th>

<th>

n

</th>

<td>

0.087413

</td>

<td>

0.181818

</td>

<td>

0.174825

</td>

<td>

0.262238

</td>

<td>

0.157343

</td>

<td>

0.090909

</td>

<td>

0.045455

</td>

</tr>

<tr>

<th rowspan="8" valign="top">

Ideal

</th>

<th>

I1

</th>

<th>

n

</th>

<td>

0.089041

</td>

<td>

0.123288

</td>

<td>

0.287671

</td>

<td>

0.109589

</td>

<td>

0.260274

</td>

<td>

0.116438

</td>

<td>

0.013699

</td>

</tr>

<tr>

<th>

IF

</th>

<th>

n

</th>

<td>

0.023102

</td>

<td>

0.065182

</td>

<td>

0.221122

</td>

<td>

0.405116

</td>

<td>

0.186469

</td>

<td>

0.078383

</td>

<td>

0.020627

</td>

</tr>

<tr>

<th>

SI1

</th>

<th>

n

</th>

<td>

0.172349

</td>

<td>

0.178888

</td>

<td>

0.141990

</td>

<td>

0.154134

</td>

<td>

0.178188

</td>

<td>

0.117702

</td>

<td>

0.056749

</td>

</tr>

<tr>

<th>

SI2

</th>

<th>

n

</th>

<td>

0.137028

</td>

<td>

0.180523

</td>

<td>

0.174365

</td>

<td>

0.187067

</td>

<td>

0.173210

</td>

<td>

0.105466

</td>

<td>

0.042340

</td>

</tr>

<tr>

<th>

VS1

</th>

<th>

n

</th>

<td>

0.097799

</td>

<td>

0.165227

</td>

<td>

0.171636

</td>

<td>

0.265534

</td>

<td>

0.130120

</td>

<td>

0.113681

</td>

<td>

0.056004

</td>

</tr>

<tr>

<th>

VS2

</th>

<th>

n

</th>

<td>

0.181424

</td>

<td>

0.224019

</td>

<td>

0.173339

</td>

<td>

0.179452

</td>

<td>

0.109643

</td>

<td>

0.086373

</td>

<td>

0.045750

</td>

</tr>

<tr>

<th>

VVS1

</th>

<th>

n

</th>

<td>

0.070347

</td>

<td>

0.163654

</td>

<td>

0.214949

</td>

<td>

0.290181

</td>

<td>

0.159257

</td>

<td>

0.087445

</td>

<td>

0.014167

</td>

</tr>

<tr>

<th>

VVS2

</th>

<th>

n

</th>

<td>

0.108979

</td>

<td>

0.194551

</td>

<td>

0.199540

</td>

<td>

0.297007

</td>

<td>

0.110898

</td>

<td>

0.068304

</td>

<td>

0.020721

</td>

</tr>

<tr>

<th rowspan="8" valign="top">

Premium

</th>

<th>

I1

</th>

<th>

n

</th>

<td>

0.058537

</td>

<td>

0.146341

</td>

<td>

0.165854

</td>

<td>

0.224390

</td>

<td>

0.224390

</td>

<td>

0.117073

</td>

<td>

0.063415

</td>

</tr>

<tr>

<th>

IF

</th>

<th>

n

</th>

<td>

0.043478

</td>

<td>

0.117391

</td>

<td>

0.134783

</td>

<td>

0.378261

</td>

<td>

0.173913

</td>

<td>

0.100000

</td>

<td>

0.052174

</td>

</tr>

<tr>

<th>

SI1

</th>

<th>

n

</th>

<td>

0.155524

</td>

<td>

0.171748

</td>

<td>

0.170070

</td>

<td>

0.158322

</td>

<td>

0.183217

</td>

<td>

0.102657

</td>

<td>

0.058462

</td>

</tr>

<tr>

<th>

SI2

</th>

<th>

n

</th>

<td>

0.142760

</td>

<td>

0.175992

</td>

<td>

0.177348

</td>

<td>

0.166836

</td>

<td>

0.176670

</td>

<td>

0.105799

</td>

<td>

0.054595

</td>

</tr>

<tr>

<th>

VS1

</th>

<th>

n

</th>

<td>

0.065862

</td>

<td>

0.146807

</td>

<td>

0.145802

</td>

<td>

0.284565

</td>

<td>

0.168929

</td>

<td>

0.111111

</td>

<td>

0.076923

</td>

</tr>

<tr>

<th>

VS2

</th>

<th>

n

</th>

<td>

0.100983

</td>

<td>

0.187370

</td>

<td>

0.184391

</td>

<td>

0.214775

</td>

<td>

0.158475

</td>

<td>

0.093834

</td>

<td>

0.060173

</td>

</tr>

<tr>

<th>

VVS1

</th>

<th>

n

</th>

<td>

0.064935

</td>

<td>

0.170455

</td>

<td>

0.129870

</td>

<td>

0.277597

</td>

<td>

0.181818

</td>

<td>

0.136364

</td>

<td>

0.038961

</td>

</tr>

<tr>

<th>

VVS2

</th>

<th>

n

</th>

<td>

0.108046

</td>

<td>

0.139080

</td>

<td>

0.167816

</td>

<td>

0.316092

</td>

<td>

0.135632

</td>

<td>

0.094253

</td>

<td>

0.039080

</td>

</tr>

<tr>

<th rowspan="8" valign="top">

Very Good

</th>

<th>

I1

</th>

<th>

n

</th>

<td>

0.059524

</td>

<td>

0.261905

</td>

<td>

0.154762

</td>

<td>

0.190476

</td>

<td>

0.142857

</td>

<td>

0.095238

</td>

<td>

0.095238

</td>

</tr>

<tr>

<th>

IF

</th>

<th>

n

</th>

<td>

0.085821

</td>

<td>

0.160448

</td>

<td>

0.250000

</td>

<td>

0.294776

</td>

<td>

0.108209

</td>

<td>

0.070896

</td>

<td>

0.029851

</td>

</tr>

<tr>

<th>

SI1

</th>

<th>

n

</th>

<td>

0.152469

</td>

<td>

0.193210

</td>

<td>

0.172531

</td>

<td>

0.146296

</td>

<td>

0.168827

</td>

<td>

0.110494

</td>

<td>

0.056173

</td>

</tr>

<tr>

<th>

SI2

</th>

<th>

n

</th>

<td>

0.149524

</td>

<td>

0.211905

</td>

<td>

0.163333

</td>

<td>

0.155714

</td>

<td>

0.163333

</td>

<td>

0.095238

</td>

<td>

0.060952

</td>

</tr>

<tr>

<th>

VS1

</th>

<th>

n

</th>

<td>

0.098592

</td>

<td>

0.165070

</td>

<td>

0.165070

</td>

<td>

0.243380

</td>

<td>

0.144789

</td>

<td>

0.115493

</td>

<td>

0.067606

</td>

</tr>

<tr>

<th>

VS2

</th>

<th>

n

</th>

<td>

0.119259

</td>

<td>

0.194134

</td>

<td>

0.179853

</td>

<td>

0.184871

</td>

<td>

0.145118

</td>

<td>

0.105751

</td>

<td>

0.071015

</td>

</tr>

<tr>

<th>

VVS1

</th>

<th>

n

</th>

<td>

0.065906

</td>

<td>

0.215463

</td>

<td>

0.220532

</td>

<td>

0.240811

</td>

<td>

0.145754

</td>

<td>

0.087452

</td>

<td>

0.024081

</td>

</tr>

<tr>

<th>

VVS2

</th>

<th>

n

</th>

<td>

0.114170

</td>

<td>

0.241296

</td>

<td>

0.201619

</td>

<td>

0.244534

</td>

<td>

0.117409

</td>

<td>

0.057490

</td>

<td>

0.023482

</td>

</tr>

</tbody>

</table>

</div>

</details>

``` python
df_raw.groupby(['cut']).apply(lambda x: pd.DataFrame(x.groupby('color')['n'].sum()/x['n'].sum()).T)
```

<div>

<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table border="1" class="dataframe">

<thead>

<tr style="text-align: right;">

<th>

</th>

<th>

color

</th>

<th>

D

</th>

<th>

E

</th>

<th>

F

</th>

<th>

G

</th>

<th>

H

</th>

<th>

I

</th>

<th>

J

</th>

</tr>

<tr>

<th>

cut

</th>

<th>

</th>

<th>

</th>

<th>

</th>

<th>

</th>

<th>

</th>

<th>

</th>

<th>

</th>

<th>

</th>

</tr>

</thead>

<tbody>

<tr>

<th>

Fair

</th>

<th>

n

</th>

<td>

0.101242

</td>

<td>

0.139130

</td>

<td>

0.193789

</td>

<td>

0.195031

</td>

<td>

0.188199

</td>

<td>

0.108696

</td>

<td>

0.073913

</td>

</tr>

<tr>

<th>

Good

</th>

<th>

n

</th>

<td>

0.134937

</td>

<td>

0.190175

</td>

<td>

0.185283

</td>

<td>

0.177538

</td>

<td>

0.143090

</td>

<td>

0.106400

</td>

<td>

0.062576

</td>

</tr>

<tr>

<th>

Ideal

</th>

<th>

n

</th>

<td>

0.131502

</td>

<td>

0.181105

</td>

<td>

0.177532

</td>

<td>

0.226625

</td>

<td>

0.144541

</td>

<td>

0.097118

</td>

<td>

0.041576

</td>

</tr>

<tr>

<th>

Premium

</th>

<th>

n

</th>

<td>

0.116235

</td>

<td>

0.169458

</td>

<td>

0.169023

</td>

<td>

0.212022

</td>

<td>

0.171126

</td>

<td>

0.103546

</td>

<td>

0.058589

</td>

</tr>

<tr>

<th>

Very Good

</th>

<th>

n

</th>

<td>

0.125228

</td>

<td>

0.198643

</td>

<td>

0.179109

</td>

<td>

0.190283

</td>

<td>

0.150968

</td>

<td>

0.099652

</td>

<td>

0.056117

</td>

</tr>

</tbody>

</table>

</div>
